"""domain models

Revision ID: a0c2e1b8d051
Revises: f6d9402682da
Create Date: 2026-04-01 17:40:38.370315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0c2e1b8d051'
down_revision: Union[str, Sequence[str], None] = 'f6d9402682da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_name'), 'workspace', ['name'], unique=True)
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('claim_type', sa.Enum('RETURN', 'DISPUTE', 'WARRANTY', name='claimtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COLLECTING_EVIDENCE', 'READY_TO_EXPORT', 'SUBMITTED', 'RESOLVED', 'CLOSED', name='casestatus'), nullable=False),
    sa.Column('counterparty_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('merchant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('incident_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_workspace_id'), 'case', ['workspace_id'], unique=False)
    op.create_table('caseexport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('export_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caseexport_case_id'), 'caseexport', ['case_id'], unique=False)
    op.drop_table('claim')
    op.add_column('auditevent', sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('auditevent', sa.Column('entity_id', sa.Integer(), nullable=False))
    op.add_column('auditevent', sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'INTEGRATION', name='actortype'), nullable=False))
    op.add_column('auditevent', sa.Column('actor_id', sa.Integer(), nullable=True))
    op.add_column('auditevent', sa.Column('happened_at', sa.DateTime(), nullable=False))
    op.add_column('auditevent', sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=False))
    op.drop_constraint(None, 'auditevent', type_='foreignkey')
    op.drop_column('auditevent', 'actor')
    op.drop_column('auditevent', 'created_at')
    op.drop_column('auditevent', 'claim_id')
    op.add_column('evidenceitem', sa.Column('case_id', sa.Integer(), nullable=False))
    op.add_column('evidenceitem', sa.Column('kind', sa.Enum('RECEIPT', 'SCREENSHOT', 'EMAIL_PDF', 'TRACKING_DOC', 'CHAT_EXPORT', 'PHOTO', 'NOTE', 'OTHER', name='evidencekind'), nullable=False))
    op.add_column('evidenceitem', sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('evidenceitem', sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('evidenceitem', sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('evidenceitem', sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('evidenceitem', sa.Column('size_bytes', sa.Integer(), nullable=False))
    op.add_column('evidenceitem', sa.Column('source_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidenceitem', sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidenceitem', sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=False))
    op.create_index(op.f('ix_evidenceitem_case_id'), 'evidenceitem', ['case_id'], unique=False)
    op.drop_constraint(None, 'evidenceitem', type_='foreignkey')
    op.create_foreign_key(None, 'evidenceitem', 'case', ['case_id'], ['id'])
    op.drop_column('evidenceitem', 'claim_id')
    op.drop_column('evidenceitem', 'filename')
    op.drop_column('evidenceitem', 'evidence_type')
    op.drop_column('evidenceitem', 'content_type')
    op.add_column('timelineevent', sa.Column('case_id', sa.Integer(), nullable=False))
    op.add_column('timelineevent', sa.Column('happened_at', sa.DateTime(), nullable=False))
    op.add_column('timelineevent', sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'INTEGRATION', name='actortype'), nullable=False))
    op.add_column('timelineevent', sa.Column('actor_id', sa.Integer(), nullable=True))
    op.add_column('timelineevent', sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('timelineevent', sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=False))
    op.create_index(op.f('ix_timelineevent_case_id'), 'timelineevent', ['case_id'], unique=False)
    op.drop_constraint(None, 'timelineevent', type_='foreignkey')
    op.create_foreign_key(None, 'timelineevent', 'case', ['case_id'], ['id'])
    op.drop_column('timelineevent', 'created_at')
    op.drop_column('timelineevent', 'description')
    op.drop_column('timelineevent', 'claim_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelineevent', sa.Column('claim_id', sa.INTEGER(), nullable=False))
    op.add_column('timelineevent', sa.Column('description', sa.VARCHAR(), nullable=False))
    op.add_column('timelineevent', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.drop_constraint(None, 'timelineevent', type_='foreignkey')
    op.create_foreign_key(None, 'timelineevent', 'claim', ['claim_id'], ['id'])
    op.drop_index(op.f('ix_timelineevent_case_id'), table_name='timelineevent')
    op.drop_column('timelineevent', 'metadata_json')
    op.drop_column('timelineevent', 'body')
    op.drop_column('timelineevent', 'actor_id')
    op.drop_column('timelineevent', 'actor_type')
    op.drop_column('timelineevent', 'happened_at')
    op.drop_column('timelineevent', 'case_id')
    op.add_column('evidenceitem', sa.Column('content_type', sa.VARCHAR(), nullable=False))
    op.add_column('evidenceitem', sa.Column('evidence_type', sa.VARCHAR(), nullable=False))
    op.add_column('evidenceitem', sa.Column('filename', sa.VARCHAR(), nullable=False))
    op.add_column('evidenceitem', sa.Column('claim_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'evidenceitem', type_='foreignkey')
    op.create_foreign_key(None, 'evidenceitem', 'claim', ['claim_id'], ['id'])
    op.drop_index(op.f('ix_evidenceitem_case_id'), table_name='evidenceitem')
    op.drop_column('evidenceitem', 'metadata_json')
    op.drop_column('evidenceitem', 'extracted_text')
    op.drop_column('evidenceitem', 'source_label')
    op.drop_column('evidenceitem', 'size_bytes')
    op.drop_column('evidenceitem', 'sha256')
    op.drop_column('evidenceitem', 'mime_type')
    op.drop_column('evidenceitem', 'storage_key')
    op.drop_column('evidenceitem', 'original_filename')
    op.drop_column('evidenceitem', 'kind')
    op.drop_column('evidenceitem', 'case_id')
    op.add_column('auditevent', sa.Column('claim_id', sa.INTEGER(), nullable=True))
    op.add_column('auditevent', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.add_column('auditevent', sa.Column('actor', sa.VARCHAR(), nullable=False))
    op.create_foreign_key(None, 'auditevent', 'claim', ['claim_id'], ['id'])
    op.drop_column('auditevent', 'metadata_json')
    op.drop_column('auditevent', 'happened_at')
    op.drop_column('auditevent', 'actor_id')
    op.drop_column('auditevent', 'actor_type')
    op.drop_column('auditevent', 'entity_id')
    op.drop_column('auditevent', 'entity_type')
    op.create_table('claim',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('claim_type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('status', sa.VARCHAR(length=14), nullable=False),
    sa.Column('created_by', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_caseexport_case_id'), table_name='caseexport')
    op.drop_table('caseexport')
    op.drop_index(op.f('ix_case_workspace_id'), table_name='case')
    op.drop_table('case')
    op.drop_index(op.f('ix_workspace_name'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
